---
openapi: 3.0.1
info:
  title: Guild API
  version: v1
paths:
  "/conversations":
    post:
      summary: Create a Conversation
      tags:
      - Conversations
      parameters: []
      responses:
        '201':
          description: conversation created
          content: {}
        '400':
          description: invalid request
          content: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                sender_id:
                  type: integer
                recipient_id:
                  type: integer
              required:
              - sender_id
              - receipient_id
  "/users":
    post:
      summary: Create a User
      tags:
      - Users
      parameters: []
      responses:
        '201':
          description: user created
          content: {}
        '400':
          description: invalid request
          content: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
              required:
              - name
              - email
servers:
- url: https://guild-api.herokuapp.com
