---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/users":
    post:
      summary: Create a User
      tags:
      - Users
      parameters: []
      responses:
        '201':
          description: user created
          content: {}
        '400':
          description: invalid request
          content: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
              required:
              - name
              - email
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
